site_name: Passgen

copyright: 'Copyright &copy; 2019 Patrick M. Elsen'

repo_name: 'xfbs/passgen'
repo_url: 'https://github.com/xfbs/passgen'

theme:
  name: 'material'
  palette:
    primary: 'blue grey'
    accent: 'blue'
  logo:
    icon: 'lock'

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true

